name: Rich Fabritius
favicon: null
layout_spectrum: 0.5493531327228993
typography_spectrum: 0.9805762157775462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9285027564037591
  lightness: 0.07635168870911002
  saturation: 0.6606433815322816
  rhythmicContrast: 0.1667923869099468
purpose: []
